dist: xenial
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "jNQNE/42SubLQm33ryIq572LM8a/cKt57H3yQz1rPQzIeAeG8LPAFurOyQB2oJVSAdGRiobLRB55/UCgojrMZOHcFNN88J0m+WYzZHJED5hbpiM0uR6cf6iXpIozNcUrF8sutsNN8VFW9CLDj+9pi
+Hy+McduGGk+72cho2PLrpsc07zOOe8zygi9YpBUDra+k3vYK4sqqk72ncDhRu4isiGtb8N6iZTh4/upJtErHvp3DVS3MVffcTQG+i67h4JL0+/0MpTg/sydvhFLo91eobKPgli+5KSV/m2M9DtfVa2OQJVQSngF
RxE7LZwaR3Y4J7bThWcgD+MLImoWywti7pmdolpBp5FOs+DUn5G8/5mKHHiqLlAvxQdr04WACdq42AR7v1yrsyY2ntGcDN1+xoAuMSGuyv1AGnkupwcTpk9AY/dCvR1O+Clkzc8jmDjYkwt5HMELUuACWeikKDOE
5V/gwp83x6hK6r0IJjWoQtLXBU7FsOBhTN5P7/WGUZ3xkNwJyi/cr3btoySlSZ9SIZbDhiokL/fwPT0mQYadrbCdO02gWSpJweTq8XGyaKHB8SLag2QMqJR5NjJVLR9uOoAeGgCFYmO5CmFhc0D/YvFfpRRaeZDV
YB+j8Zrz6aLgoHCtW1TXhSb/htklsVBhyB0fBj18nRizf8kN+1IX8k="
  
install:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U -P jdeps
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: oraclejdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk12
      script:
        - mvn test -B
